const appded=[
    {
        name:"belkjnbe1312",
        time:"15h ago",
        secret:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, animi distinctio suscipit itaque quos debitis repudiandae voluptatibus voluptas officia quibusdam neque soluta magnam quo sequi. Nihil beatae asperiores dicta quos. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio nulla, sit obcaecati nesciunt quisquam vitae error excepturi porro rerum consequatur maxime, fuga perferendis perspiciatis adipisci recusandae autem quia. Commodi iure quam tenetur. Natus placeat quae odio illum, corrupti aspernatur quod culpa rerum voluptatem unde quasi nam nesciunt est, quaerat dolor porro repellendus vel eius itaque debitis facilis at quas ut? Minima voluptatum officia necessitatibus repudiandae delectus beatae nihil, perspiciatis cumque. Minima dolorem corporis sint porro perspiciatis, tempora ea ipsum reiciendis aspernatur, consequatur consequuntur enim suscipit distinctio facere libero! Iste sunt vero nesciunt officia voluptatum similique aspernatur deserunt velit fugit excepturi?"
    },
    {
        name:"belkjnbe1312",
        time:"15h ago",
        secret:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, animi distinctio suscipit itaque quos debitis repudiandae voluptatibus voluptas officia quibusdam neque soluta magnam quo sequi. Nihil beatae asperiores dicta quos. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio nulla, sit obcaecati nesciunt quisquam vitae error excepturi porro rerum consequatur maxime, fuga perferendis perspiciatis adipisci recusandae autem quia. Commodi iure quam tenetur. Natus placeat quae odio illum, corrupti aspernatur quod culpa rerum voluptatem unde quasi nam nesciunt est, quaerat dolor porro repellendus vel eius itaque debitis facilis at quas ut? Minima voluptatum officia necessitatibus repudiandae delectus beatae nihil, perspiciatis cumque. Minima dolorem corporis sint porro perspiciatis, tempora ea ipsum reiciendis aspernatur, consequatur consequuntur enim suscipit distinctio facere libero! Iste sunt vero nesciunt officia voluptatum similique aspernatur deserunt velit fugit excepturi?"
    },
    {
        name:"belkjnbe1312",
        time:"15h ago",
        secret:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, animi distinctio suscipit itaque quos debitis repudiandae voluptatibus voluptas officia quibusdam neque soluta magnam quo sequi. Nihil beatae asperiores dicta quos. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio nulla, sit obcaecati nesciunt quisquam vitae error excepturi porro rerum consequatur maxime, fuga perferendis perspiciatis adipisci recusandae autem quia. Commodi iure quam tenetur. Natus placeat quae odio illum, corrupti aspernatur quod culpa rerum voluptatem unde quasi nam nesciunt est, quaerat dolor porro repellendus vel eius itaque debitis facilis at quas ut? Minima voluptatum officia necessitatibus repudiandae delectus beatae nihil, perspiciatis cumque. Minima dolorem corporis sint porro perspiciatis, tempora ea ipsum reiciendis aspernatur, consequatur consequuntur enim suscipit distinctio facere libero! Iste sunt vero nesciunt officia voluptatum similique aspernatur deserunt velit fugit excepturi?"
    },
    {
        name:"belkjnbe1312",
        time:"15h ago",
        secret:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, animi distinctio suscipit itaque quos debitis repudiandae voluptatibus voluptas officia quibusdam neque soluta magnam quo sequi. Nihil beatae asperiores dicta quos. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio nulla, sit obcaecati nesciunt quisquam vitae error excepturi porro rerum consequatur maxime, fuga perferendis perspiciatis adipisci recusandae autem quia. Commodi iure quam tenetur. Natus placeat quae odio illum, corrupti aspernatur quod culpa rerum voluptatem unde quasi nam nesciunt est, quaerat dolor porro repellendus vel eius itaque debitis facilis at quas ut? Minima voluptatum officia necessitatibus repudiandae delectus beatae nihil, perspiciatis cumque. Minima dolorem corporis sint porro perspiciatis, tempora ea ipsum reiciendis aspernatur, consequatur consequuntur enim suscipit distinctio facere libero! Iste sunt vero nesciunt officia voluptatum similique aspernatur deserunt velit fugit excepturi?"
    },
    {
        name:"belkjnbe1312",
        time:"15h ago",
        secret:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, animi distinctio suscipit itaque quos debitis repudiandae voluptatibus voluptas officia quibusdam neque soluta magnam quo sequi. Nihil beatae asperiores dicta quos. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio nulla, sit obcaecati nesciunt quisquam vitae error excepturi porro rerum consequatur maxime, fuga perferendis perspiciatis adipisci recusandae autem quia. Commodi iure quam tenetur. Natus placeat quae odio illum, corrupti aspernatur quod culpa rerum voluptatem unde quasi nam nesciunt est, quaerat dolor porro repellendus vel eius itaque debitis facilis at quas ut? Minima voluptatum officia necessitatibus repudiandae delectus beatae nihil, perspiciatis cumque. Minima dolorem corporis sint porro perspiciatis, tempora ea ipsum reiciendis aspernatur, consequatur consequuntur enim suscipit distinctio facere libero! Iste sunt vero nesciunt officia voluptatum similique aspernatur deserunt velit fugit excepturi?"
    },
    {
        name:"belkjnbe1312",
        time:"15h ago",
        secret:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, animi distinctio suscipit itaque quos debitis repudiandae voluptatibus voluptas officia quibusdam neque soluta magnam quo sequi. Nihil beatae asperiores dicta quos. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio nulla, sit obcaecati nesciunt quisquam vitae error excepturi porro rerum consequatur maxime, fuga perferendis perspiciatis adipisci recusandae autem quia. Commodi iure quam tenetur. Natus placeat quae odio illum, corrupti aspernatur quod culpa rerum voluptatem unde quasi nam nesciunt est, quaerat dolor porro repellendus vel eius itaque debitis facilis at quas ut? Minima voluptatum officia necessitatibus repudiandae delectus beatae nihil, perspiciatis cumque. Minima dolorem corporis sint porro perspiciatis, tempora ea ipsum reiciendis aspernatur, consequatur consequuntur enim suscipit distinctio facere libero! Iste sunt vero nesciunt officia voluptatum similique aspernatur deserunt velit fugit excepturi?"
    },
    {
        name:"belkjnbe1312",
        time:"15h ago",
        secret:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, animi distinctio suscipit itaque quos debitis repudiandae voluptatibus voluptas officia quibusdam neque soluta magnam quo sequi. Nihil beatae asperiores dicta quos. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio nulla, sit obcaecati nesciunt quisquam vitae error excepturi porro rerum consequatur maxime, fuga perferendis perspiciatis adipisci recusandae autem quia. Commodi iure quam tenetur. Natus placeat quae odio illum, corrupti aspernatur quod culpa rerum voluptatem unde quasi nam nesciunt est, quaerat dolor porro repellendus vel eius itaque debitis facilis at quas ut? Minima voluptatum officia necessitatibus repudiandae delectus beatae nihil, perspiciatis cumque. Minima dolorem corporis sint porro perspiciatis, tempora ea ipsum reiciendis aspernatur, consequatur consequuntur enim suscipit distinctio facere libero! Iste sunt vero nesciunt officia voluptatum similique aspernatur deserunt velit fugit excepturi?"
    },
    {
        name:"belkjnbe1312",
        time:"15h ago",
        secret:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, animi distinctio suscipit itaque quos debitis repudiandae voluptatibus voluptas officia quibusdam neque soluta magnam quo sequi. Nihil beatae asperiores dicta quos. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio nulla, sit obcaecati nesciunt quisquam vitae error excepturi porro rerum consequatur maxime, fuga perferendis perspiciatis adipisci recusandae autem quia. Commodi iure quam tenetur. Natus placeat quae odio illum, corrupti aspernatur quod culpa rerum voluptatem unde quasi nam nesciunt est, quaerat dolor porro repellendus vel eius itaque debitis facilis at quas ut? Minima voluptatum officia necessitatibus repudiandae delectus beatae nihil, perspiciatis cumque. Minima dolorem corporis sint porro perspiciatis, tempora ea ipsum reiciendis aspernatur, consequatur consequuntur enim suscipit distinctio facere libero! Iste sunt vero nesciunt officia voluptatum similique aspernatur deserunt velit fugit excepturi?"
    },
    {
        name:"belkjnbe1312",
        time:"15h ago",
        secret:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, animi distinctio suscipit itaque quos debitis repudiandae voluptatibus voluptas officia quibusdam neque soluta magnam quo sequi. Nihil beatae asperiores dicta quos. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio nulla, sit obcaecati nesciunt quisquam vitae error excepturi porro rerum consequatur maxime, fuga perferendis perspiciatis adipisci recusandae autem quia. Commodi iure quam tenetur. Natus placeat quae odio illum, corrupti aspernatur quod culpa rerum voluptatem unde quasi nam nesciunt est, quaerat dolor porro repellendus vel eius itaque debitis facilis at quas ut? Minima voluptatum officia necessitatibus repudiandae delectus beatae nihil, perspiciatis cumque. Minima dolorem corporis sint porro perspiciatis, tempora ea ipsum reiciendis aspernatur, consequatur consequuntur enim suscipit distinctio facere libero! Iste sunt vero nesciunt officia voluptatum similique aspernatur deserunt velit fugit excepturi?"
    },
    {
        name:"belkjnbe1312",
        time:"15h ago",
        secret:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, animi distinctio suscipit itaque quos debitis repudiandae voluptatibus voluptas officia quibusdam neque soluta magnam quo sequi. Nihil beatae asperiores dicta quos. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio nulla, sit obcaecati nesciunt quisquam vitae error excepturi porro rerum consequatur maxime, fuga perferendis perspiciatis adipisci recusandae autem quia. Commodi iure quam tenetur. Natus placeat quae odio illum, corrupti aspernatur quod culpa rerum voluptatem unde quasi nam nesciunt est, quaerat dolor porro repellendus vel eius itaque debitis facilis at quas ut? Minima voluptatum officia necessitatibus repudiandae delectus beatae nihil, perspiciatis cumque. Minima dolorem corporis sint porro perspiciatis, tempora ea ipsum reiciendis aspernatur, consequatur consequuntur enim suscipit distinctio facere libero! Iste sunt vero nesciunt officia voluptatum similique aspernatur deserunt velit fugit excepturi?"
    },
    
];
export default appded; 